In [80]:
import networkx as nx
import torch as th

In [81]:
g = nx.complete_graph(9).to_directed()

In [82]:
g.number_of_edges()

72

In [83]:
a = th.zeros([3,3,3,2])

In [84]:
a.size()

torch.Size([3, 3, 3, 2])

In [85]:
a[0][1][1][:] = 1

In [86]:
a[0][2][2][:] = 2

In [87]:
a[1][2][2][:] = 3
a[2][1][1][:] = 4

In [88]:
def nonzero_extractor(a):
    lx = []
    for i in range(a.size(0)):
        sum_a = th.sum(a[i], dim=-1)
        print(sum_a.size())
        lx.append(a[i, sum_a.gt(0), :])
#     sum_a = th.sum(a, dim=-1)
    
#     print(sum_a)
#     print(sum_a.size())
    
#     mask = sum_a.gt(0)
#     print(mask)
#     res = a[mask, :]
#     print(res)
#     print(res.size())
#     return res
    return lx


In [89]:
res = nonzero_extractor(a)

torch.Size([3, 3])
torch.Size([3, 3])
torch.Size([3, 3])


In [90]:
for i in res:
    print(i.size())

torch.Size([2, 2])
torch.Size([1, 2])
torch.Size([1, 2])


In [79]:
a = th.cat(res, dim=0)
printa(a.size)

NameError: name 'printa' is not defined

In [94]:
lens = th.Tensor([3,5,4])
mask = th.Tensor([[1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 0]])
max_len = max(lens)
th.arange(max_len).expand(len(lens), max_len) < lens.unsqueeze(1)

TypeError: expand(): argument 'size' must be tuple of ints, but found element of type Tensor at pos 2

In [112]:
length = th.ones(3)

In [123]:
length[0] = 3
length[1] = 4
length[2] = 5
max_len = int(th.max(length))
a = th.arange(max_len)
print(length.unsqueeze(1))
th.arange(max_len).expand(length.size(0), max_len)
#a.expand(length.size(0), max_len) < length.unsqueeze(1)
#th.arange(max_len).expand(length.size(0), max_len) < length.unsqueeze(1)

tensor([[3.],
        [4.],
        [5.]])


tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])

In [129]:
import numpy as np
np.random.seed(1)
X = th.randn(6, 4)
X_len = th.LongTensor([4, 1, 6, 3])  # length of each sequence
maxlen = X.size(1)
mask = th.arange(maxlen)[None, :] < X_len[:, None]
print(mask)

tensor([[ True,  True,  True,  True],
        [ True, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True, False]])


In [130]:
a = []
type(a) == list

True

In [131]:
a = th.Tensor(3)
type(a) == list

False